services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: fort-frontend
    container_name: frontend
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    command: "python manage.py runserver 0.0.0.0:8000"
    image: fort-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5433:5433"
    environment:
      - PGPORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
